resolver: lts-15.3

packages:
- ./

extra-deps:
- xmonad-0.15

nix:
  packages:
    - pkg-config
    - xorg.libX11
    - xorg.libXext
    - xorg.libXft
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver
