resolver: lts-17.14

packages:
- ./

extra-deps:
- X11-1.10
- xmonad-0.17

nix:
  packages:
    - pkg-config
    - xorg.libX11
    - xorg.libXext
    - xorg.libXft
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver

ghc-options:
  xmonad-contrib: '-j'
